spring:
  liquibase:
    enabled: true
  datasource:
     driver-class-name: org.postgresql.Driver
     url: jdbc:postgresql://localhost:5432/test_db
     username: postgres
     password: "postgres"
  data:
    cassandra:
      keyspace-name: bankService
      contact-points: localhost
      port: 9042
      local-datacenter: =DC1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        show_sql: false
        temp:
          use_jdbc_metadata_defaults: false
  client:
    exchange:
      baseUrl: https://api.twelvedata.com/exchange_rate?symbol=EUR/USD&apikey=demo&source=docs
